#ifndef _ENUM_H
#define _ENUM_H
enum meow{
  OK,
  ERR_SSL_FAILED,
  ERR_CONNECT_FAILED,
  ERR_RECEIVE_FAILED,
  ERR_SEND_FAILED,
  ERR_TOO_LARGE_CLOSE,
  ERR_ALREADY_CLOSED,
};
enum HTTPCODES{
  SWITCHING_PROTOCOLS = 101,
  HTTP_OK = 200,
  NotFound = 404,
  Unathorized = 401,
};
#endif
